//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/kryst/Desktop/Praca magisterska/st-grammar/st.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class stLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, LINE_COMMENT=2, COMMENT=3, WHITESPACE=4;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "LINE_COMMENT", "COMMENT", "WHITESPACE"
	};


	public stLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public stLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'id'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "LINE_COMMENT", "COMMENT", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "st.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static stLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,4,49,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,1,0,1,0,1,0,1,1,1,1,1,1,
		1,1,5,1,17,8,1,10,1,12,1,20,9,1,1,1,3,1,23,8,1,1,1,1,1,1,1,1,1,1,2,1,2,
		1,2,1,2,5,2,33,8,2,10,2,12,2,36,9,2,1,2,1,2,1,2,1,2,1,2,1,3,4,3,44,8,3,
		11,3,12,3,45,1,3,1,3,2,18,34,0,4,1,1,3,2,5,3,7,4,1,0,3,2,0,73,73,105,105,
		2,0,68,68,100,100,3,0,9,10,13,13,32,32,52,0,1,1,0,0,0,0,3,1,0,0,0,0,5,
		1,0,0,0,0,7,1,0,0,0,1,9,1,0,0,0,3,12,1,0,0,0,5,28,1,0,0,0,7,43,1,0,0,0,
		9,10,7,0,0,0,10,11,7,1,0,0,11,2,1,0,0,0,12,13,5,47,0,0,13,14,5,47,0,0,
		14,18,1,0,0,0,15,17,9,0,0,0,16,15,1,0,0,0,17,20,1,0,0,0,18,19,1,0,0,0,
		18,16,1,0,0,0,19,22,1,0,0,0,20,18,1,0,0,0,21,23,5,13,0,0,22,21,1,0,0,0,
		22,23,1,0,0,0,23,24,1,0,0,0,24,25,5,10,0,0,25,26,1,0,0,0,26,27,6,1,0,0,
		27,4,1,0,0,0,28,29,5,47,0,0,29,30,5,42,0,0,30,34,1,0,0,0,31,33,9,0,0,0,
		32,31,1,0,0,0,33,36,1,0,0,0,34,35,1,0,0,0,34,32,1,0,0,0,35,37,1,0,0,0,
		36,34,1,0,0,0,37,38,5,42,0,0,38,39,5,47,0,0,39,40,1,0,0,0,40,41,6,2,0,
		0,41,6,1,0,0,0,42,44,7,2,0,0,43,42,1,0,0,0,44,45,1,0,0,0,45,43,1,0,0,0,
		45,46,1,0,0,0,46,47,1,0,0,0,47,48,6,3,0,0,48,8,1,0,0,0,5,0,18,22,34,45,
		1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
